package http;

public enum EndPoints {
    GET_TASKS,
    GET_SUBTASKS,
    GET_EPICS,
    GET_TASK_BY_ID,
    GET_SUBTASK_BY_ID,
    GET_EPIC_BY_ID,
    DELETE_TASKS,
    DELETE_TASK_BY_ID,
    DELETE_EPICS,
    DELETE_EPIC_BY_ID,
    DELETE_SUBTASKS,
    DELETE_SUBTASK_BY_ID,
    POST_TASK,
    POST_EPIC,
    POST_SUBTASK,
    GET_SUBTASK_IN_EPIC,
    GET_HISTORY,
    GET_PRIORITIZED_TASKS,
    UNKNOWN
}
